# 特征工程
[知乎@城东](https://www.zhihu.com/question/29316149)

### Jupyter Themes 配置
[Github](https://github.com/dunovank/jupyter-themes)

jt -t grade3 -T -N -f inconsolata -ofs 10

#### 修改关键字颜色
CSS File: C:\Users\your_name\.jupyter\custom\custom.css<br>
第2654行
```css
.cm-s-ipython span.cm-keyword {
 color: #66D971;  /*713bc5*/
 font-weight: bold;  /*normal*/
}
```
color: #66D971; weight: bold

# 2 数据预处理

In [1]:
from sklearn.datasets import load_iris

In [2]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np

In [3]:
iris=load_iris()

In [4]:
data=DataFrame(iris.data,columns=['f1','f2','f3','f4'])
target=DataFrame(iris.target)

In [5]:
iris.data[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

## 2.1 无量纲化

### 2.1.1 标准化

In [6]:
from sklearn.preprocessing import StandardScaler
StandardScaler().fit_transform(iris.data)[:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

### 2.1.2 区间缩放

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
MinMaxScaler().fit_transform(iris.data)[:5]

array([[ 0.22222222,  0.625     ,  0.06779661,  0.04166667],
       [ 0.16666667,  0.41666667,  0.06779661,  0.04166667],
       [ 0.11111111,  0.5       ,  0.05084746,  0.04166667],
       [ 0.08333333,  0.45833333,  0.08474576,  0.04166667],
       [ 0.19444444,  0.66666667,  0.06779661,  0.04166667]])

In [9]:
ss=DataFrame(iris.data)[0]
((ss-ss.min())/(ss.max()-ss.min()))[:5]

0    0.222222
1    0.166667
2    0.111111
3    0.083333
4    0.194444
Name: 0, dtype: float64

### 2.1.3 归一化
按行处理，每个元素除以一个和行中每个元素有关的数字：<br>
$ x^{'}=\frac{x}{\sqrt{\sum_{j}^{m}{x[j]^{2}}}} $

In [6]:
from sklearn.preprocessing import Normalizer

In [11]:
Normalizer().fit_transform(iris.data)[:5]

array([[ 0.80377277,  0.55160877,  0.22064351,  0.0315205 ],
       [ 0.82813287,  0.50702013,  0.23660939,  0.03380134],
       [ 0.80533308,  0.54831188,  0.2227517 ,  0.03426949],
       [ 0.80003025,  0.53915082,  0.26087943,  0.03478392],
       [ 0.790965  ,  0.5694948 ,  0.2214702 ,  0.0316386 ]])

## 2.2 定量特征二值化

In [7]:
from sklearn.preprocessing import Binarizer
Binarizer(threshold=3).fit_transform(iris.data)[:5]

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.]])

## 2.3 哑编码

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
one=OneHotEncoder().fit_transform(iris.target.reshape((-1,1)))
type(one)

scipy.sparse.csr.csr_matrix

## 2.4 缺失值计算

In [10]:
from numpy import vstack, array,nan
from sklearn.preprocessing import Imputer

In [11]:
Imputer().fit_transform(vstack((iris.data,array([nan,nan,nan,nan]))))[-5:]

array([[ 6.3       ,  2.5       ,  5.        ,  1.9       ],
       [ 6.5       ,  3.        ,  5.2       ,  2.        ],
       [ 6.2       ,  3.4       ,  5.4       ,  2.3       ],
       [ 5.9       ,  3.        ,  5.1       ,  1.8       ],
       [ 5.84333333,  3.054     ,  3.75866667,  1.19866667]])

## 2.5 数据变换

多项式转换，degress=2

In [8]:
from sklearn.preprocessing import PolynomialFeatures

$(x_1,x_2,x_3,x_4) → (1,x_1,x_2,x_3,x_4, x_1^2，x_1x_2,x_1x_3,x_1x_4,x_2^2,x_2x_3,x_2x_4,x_3^4,x_3x_4,x_4^2)$

In [10]:
PolynomialFeatures().fit_transform(iris.data)[:2]

array([[  1.  ,   5.1 ,   3.5 ,   1.4 ,   0.2 ,  26.01,  17.85,   7.14,
          1.02,  12.25,   4.9 ,   0.7 ,   1.96,   0.28,   0.04],
       [  1.  ,   4.9 ,   3.  ,   1.4 ,   0.2 ,  24.01,  14.7 ,   6.86,
          0.98,   9.  ,   4.2 ,   0.6 ,   1.96,   0.28,   0.04]])

函数转换

In [13]:
from numpy import log1p   #log1p(x)=ln(1+x)
from sklearn.preprocessing import FunctionTransformer

In [15]:
FunctionTransformer(log1p).fit_transform(iris.data)[:3]

array([[ 1.80828877,  1.5040774 ,  0.87546874,  0.18232156],
       [ 1.77495235,  1.38629436,  0.87546874,  0.18232156],
       [ 1.74046617,  1.43508453,  0.83290912,  0.18232156]])

In [12]:
iris.data[:2]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2]])

# 3 特征选择

## 3.1 Filter

### 3.1.1 方差选择

In [50]:
data.var()

f1    0.685694
f2    0.188004
f3    3.113179
f4    0.582414
dtype: float64

In [59]:
from sklearn.feature_selection import VarianceThreshold

In [60]:
VarianceThreshold(threshold=0.6).fit_transform(iris.data)[:2]   
#只剩下方差大于threshold的Feature，默认返回方差非零的Feature

array([[ 5.1,  1.4],
       [ 4.9,  1.4]])

### 3.3.2 相关系数选择

[皮尔森相关系数](https://baike.baidu.com/item/%E7%9A%AE%E5%B0%94%E6%A3%AE%E7%9B%B8%E5%85%B3%E7%B3%BB%E6%95%B0)
- pearson r：是指线性相关系数

p-values=2.8904783526140542e-32
- e:exponent，指数；以10为底的指数。
- p-value： probability value
    - 实际不相关的两个参数，计算出相关的概率；
    - 由检验统计量的样本观察出的原假设可被拒绝的最小显著性水平。

P值检验法
- 概率论与数理统计(第四版)盛骤，P224(214)

SelectKBest
- SelectKBest(score_func,k=2).fit_transform(x,y)
    - score_func 返回一个ndarray时，被当做score
    - 返回两个ndarray时，前者是score，后者是pvalues

In [31]:
from scipy.stats import pearsonr
from sklearn.feature_selection import SelectKBest

In [79]:
def arr_pearson(X,Y):
    arr=array(list(map(lambda x:pearsonr(x, Y), X.T))).T
    return(arr[0],arr[1])

In [84]:
new_ft=SelectKBest(arr_pearson, k=2).fit_transform(iris.data, iris.target)
new_ft[:2]

array([[ 1.4,  0.2],
       [ 1.4,  0.2]])

In [14]:
X=iris.data
Y=iris.target

In [19]:
pearsonr(data['f1'].values,target.unstack()[0].values)

(0.78256123181008141, 2.8904783526140542e-32)

### 3.1.3 卡方检验

[$\chi^2$卡方检验的原理及应用](https://segmentfault.com/a/1190000003719712)

[特征选择之Chi卡方检验](http://www.jianshu.com/p/b670b2a23187)
- 假设X,Y不相关，计算卡方值；
- 卡方值越大，说明预期值与实际值偏离程度越大；
- 认为原假设的反面是正确的，即X,Y是相关的；
- 根据卡方值排序，选择卡方值最大的前`k`个值。

In [55]:
from sklearn.feature_selection import chi2
new_iris_data=SelectKBest(chi2,k=2).fit_transform(iris.data,iris.target)
new_iris_data[:2]

array([[ 1.4,  0.2],
       [ 1.4,  0.2]])

In [21]:
chi2(X,Y)

(array([  10.81782088,    3.59449902,  116.16984746,   67.24482759]),
 array([  4.47651499e-03,   1.65754167e-01,   5.94344354e-26,
          2.50017968e-15]))

### 3.1.4 互信息法

#### 最大信息系数法
Maximal Information coeffcient（MIC）
- 衡量两个变量相关性的参数（包含：线性，非线性）（Pearsonr只能反应线性相关性）
- MIC值与函数关系无关，仅与噪音值有关
    - 对于无噪音的直线关系和无噪音的正弦关系：MIC=1
    - 加入相同的噪音后，如果直线关系的MIC=0.7，那么正弦关系的MIC=0.7
    
参考:[最大信息系数（MIC）](http://blog.csdn.net/qtlyx/article/details/50780400)

#### python实现-`minepy`
- minepy非函数式实现，调用方法返回MIC
- 定义函数，`return(m.mic())`

In [34]:
from minepy import MINE

In [46]:
def mic(x,y):
    m=MINE()
    m.compute_score(x,y)
    return(m.mic())

In [54]:
new_fea=SelectKBest(lambda X, Y: array(list(map(lambda x:mic(x, Y), X.T))), k=2).fit_transform(iris.data, iris.target)
new_fea[:2]

array([[ 1.4,  0.2],
       [ 1.4,  0.2]])

## 3.2 Wrapper

### 3.2.1 递归特征消除法
#### RFE
Recursive Feature Elimination
循环特征选择。
- 列表项
- 特征集合有 `n` 个特征，所有的子集个数：$2^n-1$个;
- 指定一个Estimator,依次对$2^n-1$个子集特征进行训练，并根据validation error，选择过滤特征，直到剩下 `n_features_to_select`。

#### 参考资料
[scikit-learn-feature_selection模块](http://blog.sina.com.cn/s/blog_6a90ae320101a5h8.html)

In [16]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [17]:
new_wrapper=RFE(estimator=LogisticRegression(),n_features_to_select=2).fit_transform(iris.data,iris.target)
new_wrapper[:3]

array([[ 3.5,  0.2],
       [ 3. ,  0.2],
       [ 3.2,  0.2]])

### 3.2.2 基于惩罚项的特征选择法

In [6]:
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression

In [7]:
SelectFromModel(LogisticRegression(penalty='l1',C=0.1)).fit_transform(iris.data,iris.target)[:3]

array([[ 5.1,  3.5,  1.4],
       [ 4.9,  3. ,  1.4],
       [ 4.7,  3.2,  1.3]])